### ISSUE TITLE
Newest Code is broken

### ISSUE THREAD

**Issue by thornycrackers** [coverflowjs/coverflow#28]
I set up the demo from both here and the archived link and both would result in 

"Uncaught TypeError: undefined is not a function"

I grabbed the coverflow code that was working on the website from the source tab and put that in place of the coverflow.js that I got from github/the archive link and it started working. I don't know what the issue is but I figured it useful to bring it up.

**Comment by basti1253** [comment]
Hi,

thank you very much for your bug report. What browser/os are you using? Just to be sure did you use the coverflow file from dist-directory? I'll dig into this on sunday.

best regards

Sebastian

**Comment by thornycrackers** [comment]
I grabbed the coverflow from the src directory, that might be the issue right there.

**Comment by basti1253** [comment]
Yes. If you want to use the sources check out /tests directory.
