### ISSUE TITLE
IE9 Alignment issue

### ISSUE THREAD

**Issue by baj84** [coverflowjs/coverflow#30]
In IE9 the images are not aligned as per other browsers (see screenshot).

I think it has something to do with the transform?

Cheers
![samsung-ss](https://cloud.githubusercontent.com/assets/2744292/7563639/d300624c-f7d6-11e4-95dc-40b00acfe57e.jpg)

**Comment by basti1253** [comment]
Hi,

this looks broken, though I can't test it before tomorrow. Either way it would be very nice if can you provide a jsfiddle please? Thanks in advance. Did you check on our [project page](https://github.com/coverflowjs/coverflow) if it looks as broken? Did you disable compatibility view (x-ua-compatible meta => ie-edge).

thanks and best regards

Sebastian

**Comment by basti1253** [comment]
I tested the project homepage with a native ! IE8 and IE9 and everything looks as expected.
