### ISSUE TITLE
Cannot move to next coverflow item on jquery click event

### ISSUE THREAD

**Issue by kiwiluver75** [coverflowjs/coverflow#32]
This is a little strange. When I enter "$('#coverflow' ).coverflow( 'next' );" into the Chrome Console, it works perfectly and when I mapped the arrow keys to $('#coverflow' ).coverflow( 'next' ), that also worked fine. However, when I place $('#coverflow' ).coverflow( 'next' ) into the jquery click event of a child element, it does not move to the next image...

**Comment by basti1253** [comment]
Hi! Can you show the problem with a jsfiddle/plunker/.. example please? Thanks!

**Comment by kiwiluver75** [comment]
http://jsfiddle.net/aba5utwp/

The js file can be found here http://puneeth.org/javascripts/hony.js

**Comment by kiwiluver75** [comment]
I found a work around. Since the jquery click method doesn't work, I used the on method on "#coverflow" with click and the child element as parameters. Hope this helps someone in the future.

**Comment by basti1253** [comment]
Hi,

solution 1:
Use the original widgets click handler (click => next item, but only if not the current selected item is clicked) and added an extra click handler for your custom behavior. 

jsfiddle: http://jsfiddle.net/rudygotya/7q8eapr2/2/

solution 2:
disable coverflows item click handler and implement it yourself (see options.trigger.itemclick)

best regards
