### ISSUE TITLE
How can I add mousewheel throttle/debounce?

### ISSUE THREAD

**Issue by jaripp** [coverflowjs/coverflow#34]
Macbook trackpad speed is so fast that coverflow just scrolls from the start to end in one swipe.

**Comment by basti1253** [comment]
Hi,

I just committed a fix - but I can't test it myself as I don't have a macbook atm. Can you recheck if this fixes your problems (assets in dist dir)? thanks!

**Comment by jaripp** [comment]
Not seeing any new updates? https://github.com/coverflowjs/coverflow/tree/master/dist

**Comment by basti1253** [comment]
Sorry - pushed to wrong remote. It's updated now

**Comment by jaripp** [comment]
Now the whole page is also moving along scroll.

**Comment by basti1253** [comment]
Arghs. this should be fixed by now. Scroll problem fixed?

**Comment by jaripp** [comment]
Better, thanks!
I had to change debounce timeout 200 -> 15, otherwise it only scrolled one item at a time. 
On Mac Firefox the window still scrolls, on Chrome the mousewheel scrolling is little bit clumsy but will do for now. Still need to test on Windows browsers..

**Comment by basti1253** [comment]
Scroll prevention works fine over here on linux/windows firefox. Maybe a bit more defensive timeout (20/30ms) helps if scrolling on chome feels clumsy. 20ms works fine on chromium for me.

Would be really nice if you can provide a pull request after your fine tuning! cheers!
