### ISSUE TITLE
Getting started Instructions

### ISSUE THREAD

**Issue by jimlongo56** [coverflowjs/coverflow#36]
Hi, Great work on this. A bit of a struggle to get it working properly and a few questions.

First a note about the files. Even though the versions match, there are differences between the files on the Git page and the package download on the Welcome page http://coverflowjs.github.io/coverflow/  The git build is 2015-09-xx while the Welcome page package is from March 2014.  It's probably a pain to keep both those in sync, I'd consider removing the link from the Welcome page.

The getting-started instructions being so minimal led me to look at the source of the demo for help and that leads to the following questions and comments.

**Comments:** Building the demo with require just removes an easy source view at the demo.  Eventually found what require loaded in inspectorTools, and see smartresize.js required. Is this necessary, I don't see it called within coverflow.js rather a function called debounce().  Also would have saved me a couple of hours if I'd found main.js in the source to get some formatting tips, and not had to re-invent the cool #license feature from the demo (which I still haven't mastered to get right. Same goes for compressed css, the developer can do that themselves, and it just makes it harder to understand the project.

**Responsiveness:**  Without your style.css file the project is not responsive at all.  And the majority of the css requires a #wrapper div placed around the page to be effective. If it saves anyone some time add the following css to your project in addition to the coverflow.css (don't see any reason to use the #wrapper id). Without that it won't scale to mobile sizes.  Don't you think that should be part of coverflow.css?

```
.ui-coverflow-wrapper{
    height:480px;
    overflow:hidden;
}
@media only screen and (max-width:320px){
  .ui-coverflow-wrapper{
      height:200px;
      }
  }
@media only screen and (min-width:321px) and (max-width:480px){  
    .ui-coverflow-wrapper{
        height:240px;
        }
    }
@media only screen and (min-width:481px) and (max-width:767px){  
    .ui-coverflow-wrapper{
        height:280px;
        }
    }
@media only screen and (min-width:768px) and (max-width:1024px){  
    .ui-coverflow-wrapper{
        height:360px;
        }
    }

.ui-coverflow-wrapper #coverflow{
    min-height:200px;
    max-height:440px;
}
.ui-coverflow-wrapper #coverflow>img{
    width:400px;
    height:400px;
}
@media only screen and (max-width:320px){
  .ui-coverflow-wrapper #coverflow>img{
    width:160px;
    height:160px;
    }
}
@media only screen and (min-width:321px) and (max-width:480px){
  .ui-coverflow-wrapper #coverflow>img{
    width:200px;
    height:200px;
    }
}
@media only screen and (min-width:481px) and (max-width:767px){
  .ui-coverflow-wrapper #coverflow>img{
    width:240px;
    height:240px;
    }
}
@media only screen and (min-width:768px) and (max-width:1024px){
  .ui-coverflow-wrapper #coverflow>img{
    width:320px;
    height:320px;
    }
}
```

Again thanks for a great tool.

**Comment by basti1253** [comment]
Hey Jim,

thank you very much for your feedback! Yep, you are totally right, the docs could be much more detailled.

The reason the docs are shipping with requirejs is very simple: speed up page load to make the component a little bit more interesting. 
The initial intent was to provide a slick, reliable, generic plugin. The behaviour/look (page resize, component/image size) should be defined by the people using that plugin.

If you want to see a minimal integration take a look at this [jsfiddle](http://jsfiddle.net/rudygotya/7q8eapr2/2/). It should be really easy to setup the plugin itself (note to myself: this should be part of the docs).

**comments**
smartresize is not required and is only used by the demo page. Check out main.js - at the very bottom smartzesize is used to trigger the plugin resize. It's not part of this lib as smartresize can be easily implemented with lodash/underscore/.. What do you think on that topic? Should the library take care of handling window and component resize?

If you want to see the uncompressed sources please take a look at the src-directory. There's an [uncompressed less file](https://github.com/coverflowjs/coverflow/blob/master/src/css/coverflow.less), too ;) In dist dir you find the generated, minified sources you want to include in your project.

**responsiveness**
This css shouldn't be part of this library as the plugin shouldn't define the coverflow inner item size. The plugin doesn't really care about what's inside the coverflow wrapper - it just transforms any child element (whether it's an image/div/video/...). You are totally right - this topic should be treated with much more love/detail on our docs page. 

If you'd like to contribute a PR is more than welcome ;)

best regards

Sebastian

**Comment by basti1253** [comment]
> The git build is 2015-09-xx while the Welcome page package is from March 2014. It's probably a pain to keep both those in sync, I'd consider removing the link from the Welcome page.

This link is always pointing to the latest stable release. I added the jsfiddle in "getting started" instructions.
