### ISSUE TITLE
Image sizes can cause it to break

### ISSUE THREAD

**Issue by znap026** [coverflowjs/coverflow#37]
The styling can completely fall over if the height of the images aren't set correctly. for instance in one case i have to change the height of the images to max-height 60% of the container anything greater will cause it to fail. is there anyway to work this out? Is it dependent on any ratio with the width of the container?

I feel like I'm configuring something in correctly for this to be an issue. and advice? #

**Comment by basti1253** [comment]
Hi,

thanks for the bug report. On init the widget determines the size of the active item and takes that as a reference. It should be pretty failsafe if you define different image sizes for each media query, then [call the widget on window resize](https://github.com/coverflowjs/coverflow/blob/gh-pages/assets/js/main.js#L74-L76) like on the projects demo page.

Let me know if you hit a problem there.

best regards


Sebastian
