### ISSUE TITLE
AJAX Reload

### ISSUE THREAD

**Issue by paulsmithtester** [coverflowjs/coverflow#39]
How do I reload coverflow when dynamically adding elements?

**Comment by basti1253** [comment]
Hi,

easiest way is to reinitialize the coverflow. Check out jqueryui widget factory => destroy: https://api.jqueryui.com/jQuery.widget/#method-destroy Afterwards reinitialize the coverflow. You may want to show a loadingspinner in between, imagesLoaded plugin from desandro may be useful, too.

**Comment by paulsmithtester** [comment]
Hello, I did this
<button onclick="destroy()">destroy</button>
```
var $el = $( '.coverflow' ).coverflow({
		active : 3,
		visibleAside: 3
	});
function destroy(){
		$el.destroy();
		console.log('des');
	}
```

Am I doing this right?

it returns an error:

> Uncaught TypeError: $el.destroy is not a function

**Comment by basti1253** [comment]
Hi,

Every method not starting with an underscore is publicly available by calling $el.coverflow(„method name“)

To destroy any instance on a page you’d do it e.g. like that:

$(':ui-coverflow').coverflow('destroy‘)

Best regards

Sebastian
