### ISSUE TITLE
adding more gap/space to side of .ui-state-active

### ISSUE THREAD

**Issue by thepooltable** [coverflowjs/coverflow#43]
Hi,
I'm trying to make the "space" on .ui-state-active wider, while the rest kept the same width for all.
Am stuck trying to induce space while keeping it at the center.
Appreciate your help if you can take a look at this.

http://jsfiddle.net/7q8eapr2/756/
line 294 - commented code

Really appreciate your work here, it works pretty nicely as compared to other plugins out there.

**Comment by basti1253** [comment]
Hi,

you can try to toss with negative margins there.

I'm on a trip in china with rudimentary internet and will return early June. Please ping me if you still got problems then.

**Comment by thepooltable** [comment]
http://jsfiddle.net/7q8eapr2/761/ - awkward result, still couldn't balance out on both side.

i'll keep trying

**Comment by thepooltable** [comment]
couldn't achieve maintaining .active at the center. pretty much hoping for your help. Thank you.

**Comment by basti1253** [comment]
Adding extra margin to the active element seems to work. If you adjust margins by css slightly, the animation may still look ok. For a better experience one could adapt sources and create a custom build, though.

**Comment by thepooltable** [comment]
i tried adding margin in css, looks off, due to the jump in appending extra margin.
added margin via script, achieved the gap, but when moving through the slides, the .active went off the center :/

really need some real help here. Thanks in advance.
